<?php

use Illuminate\Database\Seeder;
use App\Language;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $languages = [	["code"=>"aar","name"=>"Afar"],
						["code"=>"abk","name"=>"Abkhazian"],
						["code"=>"afr","name"=>"Afrikaans"],
						["code"=>"aka","name"=>"Akan"],
						["code"=>"alb","name"=>"Albanian"],
						["code"=>"amh","name"=>"Amharic"],
						["code"=>"ara","name"=>"Arabic"],
						["code"=>"arg","name"=>"Aragonese"],
						["code"=>"arm","name"=>"Armenian"],
						["code"=>"asm","name"=>"Assamese"],
						["code"=>"ava","name"=>"Avaric"],
						["code"=>"ave","name"=>"Avestan"],
						["code"=>"aym","name"=>"Aymara"],
						["code"=>"aze","name"=>"Azerbaijani"],
						["code"=>"bak","name"=>"Bashkir"],
						["code"=>"bam","name"=>"Bambara"],
						["code"=>"baq","name"=>"Basque"],
						["code"=>"bel","name"=>"Belarusian"],
						["code"=>"ben","name"=>"Bengali"],
						["code"=>"bih","name"=>"Bihari languages"],
						["code"=>"bis","name"=>"Bislama"],
						["code"=>"bos","name"=>"Bosnian"],
						["code"=>"bre","name"=>"Breton"],
						["code"=>"bul","name"=>"Bulgarian"],
						["code"=>"bur","name"=>"Burmese"],
						["code"=>"cat","name"=>"Catalan"],
						["code"=>"cha","name"=>"Chamorro"],
						["code"=>"che","name"=>"Chechen"],
						["code"=>"chi","name"=>"Chinese"],
						["code"=>"chu","name"=>"Church Slavic"],
						["code"=>"chv","name"=>"Chuvash"],
						["code"=>"cor","name"=>"Cornish"],
						["code"=>"cos","name"=>"Corsican"],
						["code"=>"cre","name"=>"Cree"],
						["code"=>"cze","name"=>"Czech"],
						["code"=>"dan","name"=>"Danish"],
						["code"=>"div","name"=>"Divehi"],
						["code"=>"dut","name"=>"Dutch"],
						["code"=>"dzo","name"=>"Dzongkha"],
						["code"=>"eng","name"=>"English"],
						["code"=>"epo","name"=>"Esperanto"],
						["code"=>"est","name"=>"Estonian"],
						["code"=>"ewe","name"=>"Ewe"],
						["code"=>"fao","name"=>"Faroese"],
						["code"=>"fij","name"=>"Fijian"],
						["code"=>"fin","name"=>"Finnish"],
						["code"=>"fre","name"=>"French"],
						["code"=>"fry","name"=>"Western Frisian"],
						["code"=>"ful","name"=>"Fulah"],
						["code"=>"geo","name"=>"Georgian"],
						["code"=>"ger","name"=>"German"],
						["code"=>"gla","name"=>"Gaelic"],
						["code"=>"gle","name"=>"Irish"],
						["code"=>"glg","name"=>"Galician"],
						["code"=>"glv","name"=>"Manx"],
						["code"=>"gre","name"=>"Greek"],
						["code"=>"grn","name"=>"Guarani"],
						["code"=>"guj","name"=>"Gujarati"],
						["code"=>"hat","name"=>"Haitian"],
						["code"=>"hau","name"=>"Hausa"],
						["code"=>"heb","name"=>"Hebrew"],
						["code"=>"her","name"=>"Herero"],
						["code"=>"hin","name"=>"Hindi"],
						["code"=>"hmo","name"=>"Hiri Motu"],
						["code"=>"hrv","name"=>"Croatian"],
						["code"=>"hun","name"=>"Hungarian"],
						["code"=>"ibo","name"=>"Igbo"],
						["code"=>"ice","name"=>"Icelandic"],
						["code"=>"ido","name"=>"Ido"],
						["code"=>"iii","name"=>"Sichuan Yi"],
						["code"=>"iku","name"=>"Inuktitut"],
						["code"=>"ile","name"=>"Interlingue"],
						["code"=>"ina","name"=>"Interlingua"],
						["code"=>"ind","name"=>"Indonesian"],
						["code"=>"ipk","name"=>"Inupiaq"],
						["code"=>"ita","name"=>"Italian"],
						["code"=>"jav","name"=>"Javanese"],
						["code"=>"jpn","name"=>"Japanese"],
						["code"=>"kal","name"=>"Kalaallisut"],
						["code"=>"kan","name"=>"Kannada"],
						["code"=>"kas","name"=>"Kashmiri"],
						["code"=>"kau","name"=>"Kanuri"],
						["code"=>"kaz","name"=>"Kazakh"],
						["code"=>"khm","name"=>"Central Khmer"],
						["code"=>"kik","name"=>"Kikuyu"],
						["code"=>"kin","name"=>"Kinyarwanda"],
						["code"=>"kir","name"=>"Kirghiz"],
						["code"=>"kom","name"=>"Komi"],
						["code"=>"kon","name"=>"Kongo"],
						["code"=>"kor","name"=>"Korean"],
						["code"=>"kua","name"=>"Kuanyama"],
						["code"=>"kur","name"=>"Kurdish"],
						["code"=>"lao","name"=>"Lao"],
						["code"=>"lat","name"=>"Latin"],
						["code"=>"lav","name"=>"Latvian"],
						["code"=>"lim","name"=>"Limburgan"],
						["code"=>"lin","name"=>"Lingala"],
						["code"=>"lit","name"=>"Lithuanian"],
						["code"=>"ltz","name"=>"Luxembourgish"],
						["code"=>"lub","name"=>"Luba-Katanga"],
						["code"=>"lug","name"=>"Ganda"],
						["code"=>"mac","name"=>"Macedonian"],
						["code"=>"mah","name"=>"Marshallese"],
						["code"=>"mal","name"=>"Malayalam"],
						["code"=>"mao","name"=>"Maori"],
						["code"=>"mar","name"=>"Marathi"],
						["code"=>"may","name"=>"Malay"],
						["code"=>"mlg","name"=>"Malagasy"],
						["code"=>"mlt","name"=>"Maltese"],
						["code"=>"mon","name"=>"Mongolian"],
						["code"=>"nau","name"=>"Nauru"],
						["code"=>"nav","name"=>"Navajo"],
						["code"=>"nbl","name"=>"South Ndebele"],
						["code"=>"nde","name"=>"North Ndebele"],
						["code"=>"ndo","name"=>"Ndonga"],
						["code"=>"nep","name"=>"Nepali"],
						["code"=>"nno","name"=>"Norwegian Nynorsk"],
						["code"=>"nob","name"=>"Bokmål"],
						["code"=>"nor","name"=>"Norwegian"],
						["code"=>"nya","name"=>"Chichewa"],
						["code"=>"oci","name"=>"Occitan"],
						["code"=>"oji","name"=>"Ojibwa"],
						["code"=>"ori","name"=>"Oriya"],
						["code"=>"orm","name"=>"Oromo"],
						["code"=>"oss","name"=>"Ossetian"],
						["code"=>"pan","name"=>"Panjabi"],
						["code"=>"per","name"=>"Persian"],
						["code"=>"pli","name"=>"Pali"],
						["code"=>"pol","name"=>"Polish"],
						["code"=>"por","name"=>"Portuguese"],
						["code"=>"pus","name"=>"Pushto"],
						["code"=>"que","name"=>"Quechua"],
						["code"=>"roh","name"=>"Romansh"],
						["code"=>"rum","name"=>"Romanian"],
						["code"=>"run","name"=>"Rundi"],
						["code"=>"rus","name"=>"Russian"],
						["code"=>"sag","name"=>"Sango"],
						["code"=>"san","name"=>"Sanskrit"],
						["code"=>"sin","name"=>"Sinhala"],
						["code"=>"slo","name"=>"Slovak"],
						["code"=>"slv","name"=>"Slovenian"],
						["code"=>"sme","name"=>"Northern Sami"],
						["code"=>"smo","name"=>"Samoan"],
						["code"=>"sna","name"=>"Shona"],
						["code"=>"snd","name"=>"Sindhi"],
						["code"=>"som","name"=>"Somali"],
						["code"=>"sot","name"=>"Sotho"],
						["code"=>"spa","name"=>"Spanish"],
						["code"=>"srd","name"=>"Sardinian"],
						["code"=>"srp","name"=>"Serbian"],
						["code"=>"ssw","name"=>"Swati"],
						["code"=>"sun","name"=>"Sundanese"],
						["code"=>"swa","name"=>"Swahili"],
						["code"=>"swe","name"=>"Swedish"],
						["code"=>"tah","name"=>"Tahitian"],
						["code"=>"tam","name"=>"Tamil"],
						["code"=>"tat","name"=>"Tatar"],
						["code"=>"tel","name"=>"Telugu"],
						["code"=>"tgk","name"=>"Tajik"],
						["code"=>"tgl","name"=>"Tagalog"],
						["code"=>"tha","name"=>"Thai"],
						["code"=>"tib","name"=>"Tibetan"],
						["code"=>"tir","name"=>"Tigrinya"],
						["code"=>"ton","name"=>"Tonga"],
						["code"=>"tsn","name"=>"Tswana"],
						["code"=>"tso","name"=>"Tsonga"],
						["code"=>"tuk","name"=>"Turkmen"],
						["code"=>"tur","name"=>"Turkish"],
						["code"=>"twi","name"=>"Twi"],
						["code"=>"uig","name"=>"Uighur"],
						["code"=>"ukr","name"=>"Ukrainian"],
						["code"=>"urd","name"=>"Urdu"],
						["code"=>"uzb","name"=>"Uzbek"],
						["code"=>"ven","name"=>"Venda"],
						["code"=>"vie","name"=>"Vietnamese"],
						["code"=>"vol","name"=>"Volapük"],
						["code"=>"wel","name"=>"Welsh"],
						["code"=>"wln","name"=>"Walloon"],
						["code"=>"wol","name"=>"Wolof"],
						["code"=>"xho","name"=>"Xhosa"],
						["code"=>"yid","name"=>"Yiddish"],
						["code"=>"yor","name"=>"Yoruba"],
						["code"=>"zha","name"=>"Zhuang"],
						["code"=>"zul","name"=>"Zulu"]
					];

		foreach ($languages as $language) {
			Language::create(["name" => $language['name'], "code" => $language['code']]);
		}
    }
}
